export {
  AsyncCamoufox,
  Camoufox,
  CamoufoxSession,
  launchCamoufox,
  launchCamoufoxContext,
  resolveCamoufoxLaunchSpec,
  withCamoufox,
  type LaunchCamoufoxOptions,
  type ResolvedCamoufoxLaunchSpec,
} from './api.js';
export {
  CamouClient,
  createCamouClient,
  withCamouClient,
  type CamouActionResult,
  type CamouArtifactResult,
  type CamouClientOptions,
  type CamouCommandOptions,
  type CamouCookieResult,
  type CamouDebugResult,
  type CamouNetworkResult,
  type CamouOpenResult,
  type CamouPageContextResult,
  type CamouProfileResult,
  type CamouSessionResult,
  type CamouSnapshotElement,
  type CamouSnapshotResult,
  type CamouStateResult,
  type CamouStorageResult,
  type CamouTabResult,
  type CamouValueResult,
  type ClickOptions,
  type CookieSetOptions,
  type DiffScreenshotOptions,
  type DiffSnapshotOptions,
  type DiffUrlOptions,
  type DownloadOptions,
  type FindOptions,
  type KeyboardTypeOptions,
  type MouseButtonOptions,
  type NetworkRequestsOptions,
  type NetworkRouteOptions,
  type OpenOptions,
  type ReadOptions,
  type RuntimeSetting,
  type ScreenshotOptions,
  type ScrollOptions,
  type SelectOptions,
  type SessionIdOptions,
  type SnapshotOptions,
  type TargetOptions,
  type TraceStartOptions,
  type TypeOptions,
  type WaitOptions,
} from './client.js';
export {
  doctorCamoufox,
  inspectCamoufoxInstall,
  installCamoufox,
  listRemoteCamoufoxReleases,
  removeCamoufox,
  resolveRelease,
  type CamoufoxInstallInspection,
  type RemoteCamoufoxRelease,
  type ResolvedRelease,
} from './camoufox/installer.js';
export {
  listInstalledBrowsers,
  loadBrowserRegistry,
  requireInstalledBrowser,
  resolveInstalledBrowser,
  setCurrentBrowser,
  setInstalledBrowser,
  type BrowserInstallListing,
  type BrowserInstallRecord,
  type BrowserRegistry,
} from './camoufox/registry.js';
export { listCamoufoxPresets, resolveCamoufoxPresets, type CamoufoxPresetDefinition, type ResolvedPresetBundle } from './camoufox/presets.js';
export {
  describeFingerprintRegionProfiles,
  describeFingerprintScreenProfiles,
  describeFingerprintWindowProfiles,
  listFingerprintScreenProfiles,
  listFingerprintWindowProfiles,
  resolveFingerprintHelpers,
  type FingerprintGeolocationInput,
  type FingerprintHelperInput,
  type FingerprintRegionProfileDefinition,
  type FingerprintScreenProfileDefinition,
  type FingerprintScreenInput,
  type FingerprintWindowProfileDefinition,
  type FingerprintWindowInput,
  type ResolvedFingerprintHelpers,
} from './camoufox/fingerprint.js';
export { getCamoucliPaths, ensureBasePaths, ensureSessionPaths, getSessionPaths, type CamoucliPaths, type SessionPaths } from './state/paths.js';
export { resolveStateSnapshotPath } from './state/states.js';
export {
  BrowserNotInstalledError,
  CamoucliError,
  DaemonStartError,
  InstallError,
  IpcError,
  RefNotFoundError,
  SessionError,
  UnsupportedPlatformError,
  ValidationError,
  getExitCode,
  isCamoucliError,
  toErrorPayload,
  type ErrorPayload,
} from './util/errors.js';
export { Logger, getLogger, type LoggerHelperOptions, type LoggerOptions } from './util/log.js';
export type { LaunchInput, ResolvedLaunchConfig } from './camoufox/config.js';
export type { BrowserLaunchProbe, LaunchedSession, PreparedPersistentCamoufoxLaunch } from './camoufox/launcher.js';
export type { BrowserContext, Page } from 'playwright-core';
